### ISSUE TITLE
Question: compiling on iOS

### ISSUE THREAD

**Issue by alexandru-g** [GitLiveApp/firebase-kotlin-sdk#158]
Is anything extra required to compile a project on iOS (that's using this library). It keeps throwing the `ld: framework not found FirebaseFirestore` error. I've turned the internet upside down and I can't find anything. Thanks!

**Comment by YanivSos** [comment]
Have you tried including the Firebase pod?

BTW, this also happens to us, but only when running Unit tests. So frustrating - we can't run iOS tests from the common code

**Comment by Reedyuk** [comment]
> Is anything extra required to compile a project on iOS (that's using this library). It keeps throwing the `ld: framework not found FirebaseFirestore` error. I've turned the internet upside down and I can't find anything. Thanks!

Usually when you get an error like this, it means the framework is not being included in the compiled ipa. You should have a look at the framework you have included in your project and make sure its set to required and not optional.

**Comment by gbirk** [comment]
I'm having the same issue and I'm a beginner on multiplatform.

`import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("com.squareup.sqldelight")
    id("com.android.library")
}

sqldelight {
    database("eMusicLiveDatabase") {
        packageName = "com.emusiclive.db"
    }
}

kotlin {
    android()
    ios {
        binaries {
            framework {
                baseName = "shared"
            }
        }
    }

    // Block from https://github.com/cashapp/sqldelight/issues/2044#issuecomment-721299517.
    val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos") ?: false
    if (onPhone) {
        iosArm64("ios")
    } else {
        iosX64("ios")
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0-native-mt") //We need the native-mt version for iOS
                implementation("io.ktor:ktor-client-core:1.6.0")
                implementation("io.ktor:ktor-client-json:1.6.0")
                implementation("io.ktor:ktor-client-serialization:1.6.0")
                implementation("io.ktor:ktor-client-logging:1.6.0")
                implementation("com.squareup.sqldelight:runtime:1.5.0")
                implementation("com.squareup.sqldelight:coroutines-extensions:1.5.0")
                implementation("dev.gitlive:firebase-firestore:1.3.1")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val androidMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0")
                implementation("io.ktor:ktor-client-android:1.6.0")
//                implementation("io.ktor:ktor-client-logging-jvm:1.6.0")
                implementation("com.squareup.sqldelight:android-driver:1.5.0")
                implementation("com.google.android.material:material:1.3.0")
            }
        }
        val androidTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13.2")
            }
        }
        val iosMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-ios:1.6.0")
//                implementation("io.ktor:ktor-client-logging-native:1.3.2-1.4-M1-2")
                implementation("com.squareup.sqldelight:native-driver:1.5.0")
            }
        }
        val iosTest by getting
    }
}

android {
    compileSdkVersion(29)
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    defaultConfig {
        minSdkVersion(24)
        targetSdkVersion(29)
    }
}

val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks")
    from({ framework.outputDirectory })
    into(targetDir)
}

tasks.getByName("build").dependsOn(packForXcode)`

Adding "implementation("dev.gitlive:firebase-firestore:1.3.1")" throws "ld: framework not found FirebaseFirestore" when building iOS. I already have the Pods installed.

pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'

How can I make sure the framework is set as required? 

Thanks.

**Comment by iruizmar** [comment]
Same problem here. I tried to include the Pods as del dependencies of my shared module and it complains about missing module Firebase.

Any solution to this @Reedyuk? An entry on the docs about building for iOS would be good. 

Thanks!

**Comment by Reedyuk** [comment]
Fixed on 1.8.0 release

**Comment by jasontran98** [comment]
> Fixed on 1.8.0 release

e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: framework not found FirebaseFirestore

Hi @Reedyuk , I'm still facing this in 1.8.0. Do you have any solution for this?

**Comment by Reedyuk** [comment]
Try the latest 1.8.x

**Comment by Reedyuk** [comment]
Is this happening when compiling a KMP project or when compiling an xcode project? 
if its an xcode project, just add firebase via spm and it should work.
For kmp, usually i create a standalone universal framework and include it in my project.

**Comment by jasontran98** [comment]
> Is this happening when compiling a KMP project or when compiling an xcode project? if its an xcode project, just add firebase via spm and it should work. For kmp, usually i create a standalone universal framework and include it in my project.

Oh, I think we discuss it on a different page. I am using this library for KMM project.

**Comment by Reedyuk** [comment]
ok i see the potential issue.

You need to run on Kotlin 1.8.20, there is fixes in 1.8.20 which resolves this problem.

change your libs.versions to
```
kotlin = "1.8.20"
```
